"""
MIT License
Copyright (c) 2026 arpan404
See LICENSE file for full license text.

Structured reasoning trace types for agent decision auditing.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any


@dataclass(frozen=True, slots=True)
class ReasoningStep:
    """
    A single reasoning step extracted from an LLM response.

    Attributes:
        step_id: Unique identifier for this reasoning step.
        step_index: Sequential index within the reasoning trace.
        thought: The reasoning text generated by the model.
        confidence: Model's confidence in this step (0.0 to 1.0).
        tools_considered: List of tool names considered for this step.
        tools_rejected: Map of tool_name → reason for rejection.
        tools_selected: List of tool names selected for execution.
        parent_step_id: Parent reasoning step if nested (for parallel thoughts).
        metadata: Additional provider-specific metadata (e.g., tokens_used).
    """

    step_id: str
    step_index: int
    thought: str
    confidence: float = 1.0
    tools_considered: list[str] = field(default_factory=list)
    tools_rejected: dict[str, str] = field(default_factory=dict)
    tools_selected: list[str] = field(default_factory=list)
    parent_step_id: str | None = None
    metadata: dict[str, Any] = field(default_factory=dict)


@dataclass(frozen=True, slots=True)
class ReasoningTrace:
    """
    Complete reasoning trace for an agent run or step.

    Attributes:
        run_id: Run this trace belongs to.
        thread_id: Thread this trace belongs to.
        step: The agent step this trace corresponds to.
        steps: Ordered list of reasoning steps.
        model: Model that generated the reasoning.
        total_tokens: Total tokens used for reasoning (if available).
        finished_at_ms: Timestamp when reasoning completed.
    """

    run_id: str
    thread_id: str
    step: int
    steps: list[ReasoningStep] = field(default_factory=list)
    model: str | None = None
    total_tokens: int | None = None
    finished_at_ms: int | None = None


def extract_reasoning_from_response(
    response_text: str,
    *,
    run_id: str,
    thread_id: str,
    step: int,
    model: str | None = None,
    parse_thinking_blocks: bool = True,
) -> ReasoningTrace:
    """
    Extract structured reasoning steps from raw LLM response text.

    This utility parses model outputs that include explicit reasoning
    (e.g., Claude thinking blocks, OpenAI o-series reasoning).

    Args:
        response_text: Raw text from LLM response.
        run_id: Run identifier.
        thread_id: Thread identifier.
        step: Agent step number.
        model: Optional model identifier.
        parse_thinking_blocks: Whether to parse XML-style thinking blocks.

    Returns:
        ReasoningTrace with extracted steps.
    """
    import re

    steps: list[ReasoningStep] = []
    step_index = 0

    if parse_thinking_blocks:
        # Parse <thinking>...</thinking> blocks common in Claude and others
        pattern = r"<thinking[^>]*>(.*?)</thinking>"
        matches = re.findall(pattern, response_text, re.DOTALL)
        for thought in matches:
            thought = thought.strip()
            if thought:
                steps.append(
                    ReasoningStep(
                        step_id=f"{run_id}-step{step}-reasoning-{step_index}",
                        step_index=step_index,
                        thought=thought,
                        confidence=1.0,
                    )
                )
                step_index += 1

        # Remove thinking blocks from the main text
        response_text = re.sub(pattern, "", response_text, flags=re.DOTALL)

    # If no structured blocks found, treat entire remaining text as one step
    if not steps and response_text.strip():
        steps.append(
            ReasoningStep(
                step_id=f"{run_id}-step{step}-reasoning-0",
                step_index=0,
                thought=response_text.strip()[:2000],  # Truncate long reasoning
                confidence=0.8,
            )
        )

    return ReasoningTrace(
        run_id=run_id,
        thread_id=thread_id,
        step=step,
        steps=steps,
        model=model,
    )